# services:
#   - type: web
#     name: video-rails-api
#     env: ruby
#     buildCommand: "bundle install"
#     startCommand: "bundle exec puma -C config/puma.rb"
#     envVars:
#       - key: DATABASE_URL
#         fromDatabase:
#           name: video-rails-db
#           property: connectionString
#       - key: RAILS_MASTER_KEY
#         sync: false
services:
  - type: web
    name: video-rails-api
    env: ruby
    plan: free # ou outro plano que você escolher
    buildCommand: "bundle install --deployment --without development test"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: video-rails-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
        value: "0a7b52a431412fce26511d2e2e27810d"
    # opcional: define a porta se necessário
    ports:
      - port: 10000
        protocol: http
databases:
  - name: video-rails-db
    plan: free
